databases:
  - name: beatdrop-db
    databaseName: beatdrop_production
    user: beatdrop
    plan: free

services:
  - type: web
    name: beatdrop
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beatdrop-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: APP_HOST
        sync: false
