databases:
  - name: beatdrop-db
    databaseName: beatdrop_production
    user: beatdrop
    plan: free

services:
  - type: web
    name: beatdrop
    runtime: ruby
    plan: free
    buildCommand: bash ./bin/render-build.sh
    startCommand: bash ./bin/render-start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beatdrop-db
          property: connectionString
      - key: DATABASE_PORT
        value: "5432"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: APP_HOST
        sync: false
